### ISSUE TITLE
--sample-sheet example

### ISSUE THREAD

**Issue by themouldinator** [DaehwanKimLab/centrifuge#182]
Hi 

Please could you give an example of the --sample-sheet
i cant work out how to format the .tsv file for single end reads

Kind regards

Gus

**Comment by mourisl** [comment]
I've replied that in the pull request where you asked.  Maybe you missed that. It is
"For single-end sample you can use:
1 sample_read.fq.gz xxxx sample_classification.out sample_report.out

xxx is some randomly string, Centrifuge will ignore that in single-end sample case. The space between columns should be "tab" in the sheet since the format is tsv. Does this help?"

**Comment by themouldinator** [comment]
Hi Li

Hope you are doing well and having a great start to the new year.
Thanks so much for clarifying that for me, I really appreciate it.

Kind regards

Gus
